name: env1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.5.7=hbcca054_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.2.10=h9c3ff4c_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py310h06a4308_0
  - fontconfig=2.14.1=hef1e5e3_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=hf484d3e_1000
  - idna=3.4=py310h06a4308_0
  - imageio=2.31.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang=10.0.1=default_hb85057a_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=he513fc3_3
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.7.1=py310hff52083_0
  - matplotlib-base=3.7.1=py310h1128e8f_1
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py310h06a4308_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - ply=3.11=py_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.11=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - scipy=1.10.1=py310h5f9d8c6_1
  - setuptools=66.0.0=py310h06a4308_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=2.0.2=py310_cu118
  - torchtriton=2.0.0=py310
  - torchvision=0.15.2=py310_cu118
  - tornado=6.1=py310h5764c6d_3
  - typing_extensions=4.5.0=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - ./sim/digit_sim/digit_ar_sim/agility-1.1.1-py3-none-any.whl
      - absl-py==1.4.0
      - agility==1.1.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - cachetools==5.3.0
      - click==8.1.3
      - decorator==5.1.1
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - executing==1.2.0
      - frozenlist==1.3.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - glfw==2.5.9
      - google-auth==2.18.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.51.3
      - imageio-ffmpeg==0.4.9
      - ipython==8.13.2
      - jedi==0.18.2
      - jsonschema==4.17.3
      - markdown==3.4.3
      - matplotlib-inline==0.1.6
      - mediapy==1.1.6
      - mpmath==1.2.1
      - msgpack==1.0.5
      - mujoco==3.0.0
      - oauthlib==3.2.2
      - opencv-python==4.8.0.74
      - packaging==23.1
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - perlin-noise==1.12
      - pickleshare==0.7.5
      - platformdirs==3.5.1
      - prompt-toolkit==3.0.38
      - protobuf==4.23.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.15.1
      - pyopengl==3.1.6
      - pynput==1.7.6
      - pyqt5-sip==12.11.0
      - pyrsistent==0.19.3
      - pyyaml==6.0
      - ray==2.4.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - sentry-sdk==1.22.2
      - setproctitle==1.3.2
      - smmap==5.0.0
      - stack-data==0.6.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.0
      - traitlets==5.9.0
      - virtualenv==20.21.0
      - wandb==0.15.2
      - wcwidth==0.2.6
      - websockets==11.0.3
      - werkzeug==2.3.4
prefix: /home/helei/anaconda3/envs/env1
